name: Sync to GHES
on:
  push:
    branches: [ "main" ]
    tags: ["*"]
  workflow_dispatch:
    
jobs:
  push_to_ghes:
    runs-on: [self-hosted, linux, x64]
    env:
      GHES_BASE_URL: "https://github.qualcomm.com"
      GHES_OWNER: "qranium"
      GHES_REPO: "efficient-transformers"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0 

      - name: Check GHES reachability
        run: |
          set -e
          curl -I --max-time 10 "https://github.qualcomm.com"

      - name: Add GHES remote
        env:
          GHES_USER: ${{ secrets.GHES_USER }}
          GHES_PAT: ${{ secrets.GHES_PAT }}
        run: |
          set -eu pipefail
          git remote remove ghes 2>//dev/null || true
          #Recreate remote to be idempotent
          git remote add ghes "https://github.qualcomm.com/qraniumtest/efficient-transformers.git" || true
          git remote set-url ghes "https://${GHES_USER}:${GHES_PAT}@github.qualcomm.com/qraniumtest/efficient-transformers.git"
          git ls-remote ghes --heads
          echo "connectivity ok"
